spring:
    application:
        name: "config-server"
    profiles:
        active:
            - git
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/vivek-gohil/msedcl-banking-config
                    default-label: main
                    timeout: 5
                    clone-on-start: true # copy github repository on startup of application
                    force-pull: true
server:
    port: 8383

management:
    endpoints:
        web:
            exposure:
                include: "*"
