spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.url=jdbc:mysql://localhost:3306/account_db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

logging.file.name=logs/accounts.log
server.port=8181