spring:
    application:
        name: "account-service"
    datasource:
        username: root
        password: root123
        url: jdbc:mysql://localhost:3306/account_db
        driver-class-name: com.mysql.cj.jdbc.Driver
server:
    port: 8181
logging:
    file:
        name: logs/accounts.log
build:
    version: "2.0"
account:
    message: "Welcome to MSEDCL bank account reated REST API - UAT"
    contactDetails:
        name: "Shamal"
        email: "shamal@msedcl.in"
    onCallSupport:
        - 1122334455
        - 7788990066
